/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

static int courante;

int *
add_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

        courante = courante + *argp;
        printf ("courante add %d \n", courante);
        printf ("arg add %d \n", *argp);
        result = courante;
	return &result;
}

int *
mul_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

        courante = courante * *argp;
        result = courante;
	return &result;
}

void *
init_1_svc(int *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
        courante = *argp;
        printf ("courante serveur %d \n", courante);
	return (void *) &result;
}
